package SuperAdmin;
import User.User;
import Checks.checks;
import Admin.Admin;
import Admin.Admin_panel;
import DBconnect.DBConnect;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nils
 */
public class Super_Admin_Panel extends javax.swing.JFrame {
Connection con;
    Statement st;
    ResultSet rs;
    DBConnect connect = new DBConnect();
    /**
     * Creates new form Super_Admin_Panel
     */

    public Super_Admin_Panel() {
        initComponents();
        Show_Users_IN_JTable();
        
    }
    public Super_Admin_Panel(int ID,String super_admin) {
        initComponents();
        Show_Users_IN_JTable();
        id(ID,super_admin);
    }
    public void id(int ID,String super_admin){
        String temp=Integer.toString(ID);
        jTextField1.setText(temp);
        jTextField2.setText(super_admin);
    }
    public void Show_Users_IN_JTable(){
        ArrayList<User> list = getusersList();
         DefaultTableModel model= (DefaultTableModel)jTable_Display_User.getModel();
        Object[] row=new Object[5];
        
        for (int i=0;i<list.size();i++){
            row[0]=list.get(i).getID();
            row[1]=list.get(i).getFirstName();
            row[2]=list.get(i).getLastName();
            row[3]=list.get(i).getEmail();
            row[4]=list.get(i).getPassword();
         
           model.addRow(row);
        }
    } 
     public void executeSQLQuery(String query, String message){
        DBConnect connect = new DBConnect();
        connect.DBConnect();
        try{
           con = DriverManager.getConnection("jdbc:mysql://localhost/Users?serverTimezone=Europe/Riga&useSSL=false","root","");
           st=con.createStatement();
           if(st.executeUpdate(query)==1){
               DefaultTableModel model=(DefaultTableModel)jTable_Display_User.getModel();
               model.setRowCount(0);
               Show_Users_IN_JTable();

               JOptionPane.showMessageDialog(null,"Data "+message+"Succefully");
           }else{
               JOptionPane.showMessageDialog(null,"Data NOT "+message);
           }
           con.close();
           st.close();
           rs.close();
        }catch(Exception ex){
             ex.printStackTrace();
        }
    }
   public ArrayList<User> getusersList(){
        ArrayList<User> usersList=new ArrayList<>();
        connect.DBConnect();
        
        String query="Select *From `admin`";
               
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/Users?serverTimezone=Europe/Riga&useSSL=false","root","");
            st=con.createStatement();
            rs = st.executeQuery(query);
             User user;
             while(rs.next()){
                 user=new User(rs.getInt("id"),rs.getString("firstName"),rs.getString("lastName"),rs.getString("email"),rs.getString("password"));
                 usersList.add(user);
         }
            con.close();
            st.close();
            rs.close();
             
        }catch (Exception ex){
            ex.printStackTrace();
        }
        return usersList;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_Parole = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_User = new javax.swing.JTable();
        jButton_Insert = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_Vards = new javax.swing.JTextField();
        jTextField_Uzvards = new javax.swing.JTextField();
        jButton_Clear = new javax.swing.JButton();
        jTextField_Epasts = new javax.swing.JTextField();
        jTextField_oldPass = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_Parole.setBackground(new java.awt.Color(204, 255, 204));
        jTextField_Parole.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(0, 255, 102));
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));

        jTable_Display_User.setBackground(new java.awt.Color(153, 255, 204));
        jTable_Display_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Vards", "Uzvards", "E-pasts", "Parole"
            }
        ));
        jTable_Display_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_UserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_User);

        jButton_Insert.setBackground(new java.awt.Color(0, 255, 102));
        jButton_Insert.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Insert.setText("Insert");
        jButton_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertActionPerformed(evt);
            }
        });

        jButton_Update.setBackground(new java.awt.Color(0, 255, 102));
        jButton_Update.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Delete.setBackground(new java.awt.Color(0, 255, 102));
        jButton_Delete.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("ID");

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Vards");

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Uzvards");

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("E-pasts");

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Parole");

        jTextField_ID.setBackground(new java.awt.Color(204, 255, 204));
        jTextField_ID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });

        jTextField_Vards.setBackground(new java.awt.Color(204, 255, 204));
        jTextField_Vards.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextField_Uzvards.setBackground(new java.awt.Color(204, 255, 204));
        jTextField_Uzvards.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jButton_Clear.setBackground(new java.awt.Color(0, 255, 102));
        jButton_Clear.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Clear.setText("Iztīrīt");
        jButton_Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ClearMouseClicked(evt);
            }
        });
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        jTextField_Epasts.setBackground(new java.awt.Color(204, 255, 204));
        jTextField_Epasts.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jTextField_oldPass.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_oldPass.setForeground(new java.awt.Color(51, 51, 51));

        jTextField1.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButton1.setText("Atpakaļ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_ID)
                            .addComponent(jTextField_Vards)
                            .addComponent(jTextField_Uzvards)
                            .addComponent(jTextField_Epasts)
                            .addComponent(jTextField_Parole)
                            .addComponent(jTextField_oldPass, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Update)))
                        .addGap(17, 17, 17)
                        .addComponent(jButton_Delete)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_Vards, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Uzvards, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Epasts, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Parole, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_oldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jButton_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_Display_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_UserMouseClicked
        //Display Slected Row in  JtexteFields
        int i=jTable_Display_User.getSelectedRow();
        TableModel model=jTable_Display_User.getModel();
        jTextField_ID.setText(model.getValueAt(i,0).toString());
        jTextField_Vards.setText(model.getValueAt(i,1).toString());
        jTextField_Uzvards.setText(model.getValueAt(i,2).toString());
        jTextField_Epasts.setText(model.getValueAt(i,3).toString());
        jTextField_Parole.setText(model.getValueAt(i,4).toString());
        jTextField_oldPass.setText(model.getValueAt(i,4).toString());
    }//GEN-LAST:event_jTable_Display_UserMouseClicked

    private void jButton_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertActionPerformed
        try {
            checks checks=new checks();
            Admin addd=new Admin();

            String name_INPUT=jTextField_Vards.getText();
            String lastName_INPUT=jTextField_Uzvards.getText();
            String password_INPUT=jTextField_Parole.getText();
            String email_INPUT=jTextField_Epasts.getText();
            if(!checks.checkField(name_INPUT) || !checks.checkField(lastName_INPUT) || !checks.isValidword(name_INPUT) || !checks.isValidword(lastName_INPUT)|| !checks.isValidEmail(email_INPUT) || !checks.passwordCHECK(password_INPUT)){
                if(!checks.checkField(name_INPUT))
                JOptionPane.showMessageDialog(null,"Name is empty");
                if(!checks.checkField(lastName_INPUT))
                JOptionPane.showMessageDialog(null,"Last Name is empty");
                else{
                    if(!checks.isValidword(name_INPUT))
                    JOptionPane.showMessageDialog(null,"Incorrect characters contained in NAME");
                    if(!checks.isValidword(lastName_INPUT))
                    JOptionPane.showMessageDialog(null,"Incorrect characters contained  in LAST NAME");
                }
                String nosaukums="clients";
                String check_name="email";
                
                String nosaukums2="admin";
                String check_name2="email";
                if (checks.hasField(email_INPUT,nosaukums,check_name) || checks.hasField(email_INPUT,nosaukums2,check_name2))
                    JOptionPane.showMessageDialog(null,"Tads epasts jau eksiste");
                if(!checks.isValidEmail(email_INPUT))
                    JOptionPane.showMessageDialog(null,"Email error");
                if(!checks.passwordCHECK(password_INPUT))
                    JOptionPane.showMessageDialog(null,"Password must NOT BE LESS than 8 characters");
            }else {
                name_INPUT=checks.firstUpperCase(name_INPUT);
                lastName_INPUT=checks.firstUpperCase(lastName_INPUT);

                String Password=checks.passwordMD(password_INPUT);

                String name="admin";
                String query=addd.Insert_USERS(name,name_INPUT, lastName_INPUT, email_INPUT, Password);
                executeSQLQuery(query,"Inserted");
            }
        } catch (NoSuchAlgorithmException ex) {
            JOptionPane.showMessageDialog(null, "ddddddddd");
        }
    }//GEN-LAST:event_jButton_InsertActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        Admin update=new Admin();
        checks checks=new checks();

        try {

            String name_INPUT=jTextField_Vards.getText();
            String lastName_INPUT=jTextField_Uzvards.getText();
            String password_INPUT=jTextField_Parole.getText();
            String email_INPUT=jTextField_Epasts.getText();
            String old_pass= jTextField_oldPass.getText();

            if(!checks.checkField(name_INPUT) || !checks.checkField(lastName_INPUT) || !checks.isValidword(name_INPUT) || !checks.isValidword(lastName_INPUT)|| !checks.isValidEmail(email_INPUT) ){
                if(!checks.isValidword(name_INPUT))
                    JOptionPane.showMessageDialog(null,"Incorrect characters contained in NAME");
                if(!checks.isValidword(lastName_INPUT))
                    JOptionPane.showMessageDialog(null,"Incorrect characters contained  in LAST NAME");
                if(!checks.checkField(name_INPUT))
                    JOptionPane.showMessageDialog(null,"Name is empty");
                if(!checks.checkField(lastName_INPUT))
                    JOptionPane.showMessageDialog(null,"Last Name is empty");
                
                String nosaukums="clients";
                String check_name="email";
                
                String nosaukums2="admin";
                String check_name2="email";
                
                if (checks.hasField(email_INPUT,nosaukums,check_name) || checks.hasField(email_INPUT,nosaukums2,check_name2))
                    JOptionPane.showMessageDialog(null,"Tads epasts jau eksiste");
                if(!checks.isValidEmail(email_INPUT))
                    JOptionPane.showMessageDialog(null,"Email error");
                if(!checks.passwordCHECK(password_INPUT))
                    JOptionPane.showMessageDialog(null,"Password must NOT BE LESS than 8 characters");
            }else {
                if(!checks.passwordCHECK(password_INPUT,old_pass)){
                    name_INPUT=jTextField_Vards.getText();
                    lastName_INPUT=jTextField_Uzvards.getText();
                    email_INPUT=jTextField_Epasts.getText();

                    name_INPUT=checks.firstUpperCase(name_INPUT);
                    lastName_INPUT=checks.firstUpperCase(lastName_INPUT);

                    String query = "UPDATE `admin` SET `firstName`='"+name_INPUT+"',`lastName`='"+lastName_INPUT+"',`email`='"+email_INPUT+"' WHERE id = "+jTextField_ID.getText();
                    executeSQLQuery(query,"Updated");
                }else{
                    if (password_INPUT.length()<8 || password_INPUT.length()>20){JOptionPane.showMessageDialog(null,"Pass error");}
                    else{
                        name_INPUT=jTextField_Vards.getText();
                        lastName_INPUT=jTextField_Uzvards.getText();
                        email_INPUT=jTextField_Epasts.getText();
                        String Password=checks.passwordMD(password_INPUT);

                        String ID=jTextField_ID.getText();
                        String name="admin";
                        String query = update.Update_Users(name,name_INPUT, lastName_INPUT, email_INPUT, Password, ID);
                        executeSQLQuery(query,"Updated");
                    }
                }
            }
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        Admin delete=new Admin();

        String ID=jTextField_ID.getText();
        String name="admin";

        String query=delete.Delete_Users(name,ID);
        executeSQLQuery(query,"Deleted");
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    private void jButton_ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ClearMouseClicked
        jTextField_ID.setText("");
        jTextField_Vards.setText("");
        jTextField_Uzvards.setText("");
        jTextField_Epasts.setText("");
        jTextField_Parole.setText("");
        jTextField_oldPass.setText("");
    }//GEN-LAST:event_jButton_ClearMouseClicked

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
       String temp=jTextField1.getText();
       int ID=Integer.parseInt(temp);
       String super_admin=jTextField2.getText();
       Super_Admin panel=new Super_Admin((int) ID,super_admin);
       panel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Super_Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Super_Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Super_Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Super_Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Super_Admin_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Insert;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_User;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_Epasts;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Parole;
    private javax.swing.JTextField jTextField_Uzvards;
    private javax.swing.JTextField jTextField_Vards;
    private javax.swing.JTextField jTextField_oldPass;
    // End of variables declaration//GEN-END:variables

   
}
